/**
 * ============================================================================
 * DISTRITO PAULISTA RP — CAMADA CENTRALIZADA DE DADOS E DIRETRIZES
 * ============================================================================
 * Módulo único e reutilizável para compartilhar regras, estrutura RBAC,
 * perfis iniciais e mock data sem duplicação de código.
 */

export const DEFAULT_RULES = {
  gerais: {
    title: "Regras Gerais da Cidade — Distrito Paulista RP",
    content: [
      "PRINCÍPIOS DA CIDADE",
      "• Respeito mútuo entre jogadores e membros da equipe administrativa.",
      "• Valorização da vida e da interpretação do personagem acima de tudo.",
      "• Busca por um RP sério, coerente, equilibrado e imersivo.",
      "• Proibição rigorosa de qualquer forma de abuso, exploração de falhas ou atitudes Anti-RP.",
      "",
      "CAPÍTULO 1 — DISPOSIÇÕES GERAIS",
      "1.1 Conduta dos Cidadãos: Todos os jogadores devem manter postura respeitosa dentro e fora da cidade. É proibido ofender, ameaçar, constranger, humilhar ou perseguir outros jogadores.",
      "1.2 Responsabilidade da Conta: Cada conta é de responsabilidade exclusiva do jogador. Empréstimos, compartilhamentos ou uso indevido não isentam o proprietário de possíveis sanções.",
      "1.3 Respeito à Comunidade: O Distrito Paulista RP não tolera preconceito, discriminação, racismo, xenofobia, misoginia, homofobia ou qualquer outra conduta abusiva, resultando em banimento permanente.",
      "",
      "CAPÍTULO 2 — FUNDAMENTOS DO ROLEPLAY",
      "2.1 O que é Roleplay: Roleplay é a interpretação de um personagem dentro da cidade, com ações coerentes, contexto e consequências. O objetivo é representar uma vida virtual de forma crível.",
      "2.2 IC e OOC: IC (In Character) refere-se às ações e informações do personagem. OOC (Out Of Character) são informações externas, como conversas no Discord, lives e conhecimento do jogador fora do jogo.",
      "2.3 Meta Gaming (MG): É proibido utilizar informações OOC para benefício dentro do jogo, como descobrir localização por live, Discord ou terceiros.",
      "2.4 Power Gaming (PG): É proibido realizar ações impossíveis, abusivas ou sem chance de reação para outra parte, forçando o andamento de uma situação.",
      "2.5 Fail RP / Anti-RP: Qualquer ação que quebre a imersão, ignore consequências ou transforme uma situação séria em brincadeira inadequada será considerada infração.",
      "2.6 Combat Logging (CL): Combat Logging ocorre quando um jogador encerra sua conexão com a cidade de forma proposital para evitar uma situação de Roleplay, fugir de consequências ou impedir o andamento de uma ocorrência.",
      "• É proibido desconectar durante abordagens policiais;",
      "• É proibido sair da cidade durante assaltos, perseguições ou conflitos;",
      "• É proibido fechar o jogo para evitar prisão, apreensão de itens ou consequências do RP;",
      "• É proibido utilizar uma queda de conexão proposital para obter vantagem mecânica.",
      "• Queda real de conexão: Caso ocorra uma queda real de conexão, o jogador deverá retornar assim que possível e procurar os envolvidos para dar continuidade ou esclarecer a situação.",
      "• O Combat Logging prejudica diretamente a experiência dos demais jogadores e será tratado como uma infração administrativa grave.",
      "",
      "CAPÍTULO 3 — VALORIZAÇÃO DA VIDA E MORTE",
      "3.1 Valorização da Vida (VDL): Todo cidadão deve agir como se sua vida fosse real, evitando atitudes imprudentes e reagindo com medo e cautela em situações de risco.",
      "3.2 Situações de Risco: Ao estar rendido, cercado ou em nítida desvantagem, o jogador deve priorizar a própria sobrevivência e a continuidade do RP.",
      "3.3 Retorno ao Local (Revenge Kill): Após uma situação finalizada com morte, queda ou encerramento, não será permitido retornar ao local apenas para retomar o conflito imediatamente.",
      "",
      "CAPÍTULO 4 — COMBATE E AÇÕES HOSTIS",
      "4.1 RDM: É proibido derrubar, matar ou iniciar agressão contra outro jogador sem motivo e sem construção dentro do Roleplay.",
      "4.2 VDM: É proibido utilizar veículos como arma, atropelar propositalmente ou usar condução abusiva com a finalidade de causar dano injusto.",
      "4.3 Início de Conflitos: Conflitos devem possuir motivo, contexto e coerência. Discussões, rivalidades e disputas devem ser desenvolvidas por RP.",
      "",
      "CAPÍTULO 7 — VEÍCULOS E DIREÇÃO",
      "7.1 Direção Coerente: A condução de veículos deve respeitar a realidade do cenário. Dirigir sem lógica, em velocidade excessiva constante ou de forma destrutiva será considerado infração.",
      "7.2 Veículos Oficiais: Viaturas, ambulâncias e demais veículos de serviço devem ser utilizados somente dentro das atribuições permitidas.",
      "7.3 ÁREAS SAFE (ZONAS SEGURAS):",
      "• Praça Central;",
      "• Hospital Albert Einstein;",
      "• Mecânicas e Oficinas;",
      "• Concessionárias;",
      "• Garagens Funcionais;",
      "• Área interna do presídio;",
      "• Locais onde estejam ocorrendo eventos oficiais;",
      "• Restaurantes.",
      "• Regra Safezone: Proibido iniciar ações criminosas em Área Safe ou utilizá-la como refúgio para escapar de perseguição iniciada fora dela.",
      "",
      "CAPÍTULO 8 — ECONOMIA, ITENS, BENEFÍCIOS E PD/PP",
      "8.1 Exploração de Falhas: É proibido explorar bugs, duplicar itens, manipular sistemas financeiros ou obter vantagem por falha do servidor.",
      "8.2 Comércio e Benefícios: Coins, Gemas, imóveis, sistemas VIP e demais vantagens devem ser utilizados de forma legítima, sem abuso ou fraude.",
      "8.3 REGRAS VIP:",
      "• 1. Moedas VIP (Coins e Gemas): As moedas VIP são produtos digitais ativados na conta do jogador no Distrito Paulista RP após aprovação da aquisição. Ao efetuar a compra, o jogador declara ciência de que ser VIP não o torna imune às regras, sanções, suspensões ou banimentos temporários ou permanentes.",
      "• 2. Benefícios não concedem imunidade: Ser VIP não concede passe livre para cometer Anti-RP, abusar de bugs, agir de má-fé ou utilizar vantagens proibidas. Jogadores VIP estão sujeitos às mesmas regras e punições aplicáveis aos demais cidadãos.",
      "8.4 PD/PP DO PERSONAGEM:",
      "• PD do Personagem: O PD ocorre quando o personagem comete algo grave no RP, morre e perde definitivamente aquele personagem.",
      "• PP do Personagem: O PP ocorre quando o personagem comete algo grave no RP envolvendo a polícia, é punido com prisão perpétua e perde definitivamente aquele personagem.",
      "• Criação de novo personagem após PD ou PP: Ao ser punido com PD ou PP, o jogador deverá criar um personagem com nome e características diferentes. Não poderá existir vínculo de parentesco, continuidade de atividades ou reaproveitamento da mesma história do personagem anterior. A criação de personagem idêntico ou semelhante para continuar a mesma história poderá resultar em banimento permanente.",
      "• Exemplos de situações que podem levar a PD: Indícios graves de falta de apreço pela própria vida; Ser sequestrado ou assaltado e permanecer ameaçando, xingando ou debochando do sequestrador/assaltante; Estar em clara desvantagem numérica e ainda assim iniciar troca de tiros em situação de rua; Utilizar rádio ou celular de forma incompatível com uma situação de rendição diante de assaltante ou sequestrador; Sair do RP utilizando referências externas às regras ou à administração para interferir na cena.",
      "• Exemplos de situações que podem levar a PP: Questionar de forma excessiva uma abordagem policial durante o RP; Debochar de policiais durante procedimento de prisão; Questionar excessivamente procedimentos policiais durante a cena; Não respeitar ordens legais quando estiver sob ameaça armada; Cair da moto durante uma fuga e levantar atirando sem respeitar a situação; Sair do RP para reclamar de Código Penal, leis, prefeitura ou administração durante a ocorrência.",
      "• Quem pode solicitar PD ou PP: Qualquer jogador poderá solicitar a análise de um PD ou PP pela equipe administrativa, apresentando as provas e explicando o motivo do pedido. A equipe avaliará a ocorrência e decidirá se a punição é aplicável.",
      "• Veículos VIP após PD ou PP: Os veículos VIP poderão permanecer disponíveis ao novo personagem, exceto nos casos em que a equipe caracterizar PD ou PP forçado ou determinar a perda dos benefícios vinculados ao personagem.",
      "• PD ou PP forçado: A equipe analisará os pedidos de PD e PP. Caso fique caracterizado que o jogador forçou uma situação para receber PD ou PP, poderá ocorrer a perda total do que estiver relacionado ao personagem, incluindo veículos VIP, além de banimento permanente em caso de reincidência.",
      "• Orientações para evitar PD ou PP: Mantenha sempre o bom senso; Preserve a sua vida acima de tudo; Caso sofra Anti-RP, não interrompa a cena para discutir, continue o RP e abra ticket posteriormente.",
      "",
      "CAPÍTULO 9 — STAFF, DENÚNCIAS E PUNIÇÕES",
      "9.1 Autoridade Administrativa: A equipe administrativa poderá avaliar situações, aplicar punições e interpretar regras visando preservar a ordem e a qualidade do RP.",
      "9.2 Provas e Denúncias: Denúncias devem ser apresentadas com provas adequadas (vídeos com áudio e contexto completo).",
      "9.3 Punições: As sanções poderão variar entre advertência, remoção de benefícios, suspensão e banimento, conforme a gravidade da infração.",
      "",
      "CAPÍTULO 10 — DISPOSIÇÕES FINAIS",
      "10.1 Atualizações: Este regulamento poderá ser atualizado a qualquer momento para atender às necessidades do servidor.",
      "10.2 Ciência das Regras: Ao permanecer na cidade, o jogador declara ciência e concordância com as regras aqui estabelecidas.",
      "10.3 Compromisso com o RP: O Distrito Paulista Roleplay preza por uma experiência justa, séria e envolvente para todos os seus cidadãos."
    ].join("\n")
  },
  policia: {
    title: "Regulamento das Forças Policiais e Serviços de Emergência SP",
    content: [
      "CAPÍTULO 6 — SERVIÇOS PÚBLICOS",
      "",
      "6.1 REGRAS GERAIS DA POLÍCIA",
      "As regras abaixo se aplicam às forças policiais do Distrito Paulista Roleplay, observadas as atribuições, jurisdições e hierarquias próprias de cada corporação. O objetivo é preservar a coerência do RP, a segurança dos cidadãos e o bom funcionamento das ações policiais.",
      "1. Transporte de presos: Todas as organizações policiais são obrigadas a realizar o transporte dos presos até a Delegacia de Polícia Civil.",
      "2. Arsenal policial e apreensões: É extremamente proibido vender, entregar, desviar ou traficar armas pertencentes ao arsenal policial ou provenientes de apreensões. O policial flagrado nessa prática será exonerado da corporação e ficará impedido de retornar a qualquer força policial até o próximo wipe.",
      "3. Armamento fora de serviço: Quando estiver fora de serviço, o policial poderá portar somente uma Glock e, no máximo, 70 munições. Demais armamentos ou equipamentos exclusivos do serviço deverão permanecer guardados.",
      "4. Corrupção policial: Todo policial flagrado em ato de corrupção responderá pelo fato dentro do RP, será investigado e julgado conforme a situação. Caso seja exonerado em razão da corrupção, somente poderá retornar a uma corporação policial após o próximo wipe.",
      "5. Patrulhamento individual: É proibido realizar patrulhamento sozinho. Todo policial em patrulha deve estar acompanhado por, no mínimo, outro policial.",
      "6. Ponto de serviço: Policiais em serviço devem permanecer com o ponto aberto. Fora de serviço, o ponto deve permanecer fechado. O policial que estiver apenas parado no batalhão, sem exercer atividade operacional ou administrativa de serviço, será considerado fora de serviço e deverá fechar o ponto.",
      "7. Disparos contra pneus: O disparo contra pneus poderá ser autorizado quando o indivíduo: furar bloqueio de blitz; atropelar um cidadão; derrubar de forma intencional uma equipe de ROCAM ou RPM; ou praticar Power Gaming durante a ocorrência. A autorização deverá partir de um Oficial da Polícia Militar; na Polícia Civil, de Investigador-Chefe ou superior; e, na PRF, de Chefe de Equipe ou superior. O disparo deve ser utilizado com responsabilidade e proporcionalidade.",
      "8. Retorno a ações encerradas: Após sair de uma ação ou abandonar o perímetro de uma ocorrência já em andamento, o policial não poderá retornar à mesma ação, salvo determinação administrativa ou situação excepcional autorizada pelo comando responsável.",
      "9. Prioridade da polícia especializada: As unidades de polícia especializada têm obrigação e prioridade no atendimento de ocorrências envolvendo ações fechadas e incursões em favela.",
      "10. Código Penal, multas e fianças: Os policiais devem seguir as leis e procedimentos previstos no Código Penal vigente da cidade. Multas podem ser aplicadas no local da abordagem quando cabíveis; fianças, quando previstas, deverão ser tratadas na delegacia.",
      "11. Ações com reféns: Em ações com reféns, a vida do refém é a maior prioridade. Quando houver negociação com fuga limpa, é proibido abusar de barreiras e spikes para anular a fuga negociada; cercos são permitidos desde que não contrariem os termos acertados. TENHA BOM SENSO SEMPRE!",
      "12. Jurisdição e fronteira do Paraguai: A Polícia Militar, com exceção da unidade DEPAN da Polícia Ambiental, a CGM e a Polícia Civil são proibidas de ultrapassar a fronteira do Brasil e ingressar no Paraguai, pois possuem jurisdição apenas em território brasileiro. Somente a Polícia Federal (PF) e a Polícia Rodoviária Federal (PRF) poderão atuar além da fronteira, dentro das regras específicas de suas corporações.",
      "13. Revista pessoal e veicular: A Polícia Militar somente poderá realizar revista pessoal ou veicular quando houver fundada suspeita ou flagrante delito. Em abordagens exclusivamente de trânsito, a atuação deverá se limitar à verificação de documentação e irregularidades do veículo ou do condutor, salvo surgimento de fundada suspeita durante a abordagem.",
      "14. Uso de veículos pessoais em serviço: É proibido utilizar veículos pessoais durante o serviço, exceto quando houver autorização específica prevista para investigação descaracterizada ou cumprimento de mandados pela Polícia Civil.",
      "15. Colisão durante perseguição: Se um policial colidir e derrubar um jogador durante uma fuga, deverá permitir que ele retome a fuga, respeitando o Fair Play. Entretanto, se o próprio fugitivo colidir com a viatura ou provocar a colisão e ficar impossibilitado de continuar, não haverá obrigação de reiniciar a fuga.",
      "16. Cercos e bloqueios durante perseguição: É permitido realizar cercos e fechar vias com viaturas. É proibido, porém, posicionar a viatura de forma repentina diretamente à frente do fugitivo com a finalidade de provocar colisão inevitável.",
      "17. Limite de unidades em perseguição: O limite padrão é de 4 unidades policiais em uma perseguição. Equipes de RPM, com mínimo de 2 e máximo de 3 policiais, contam como uma unidade; equipes de ROCAM, com mínimo de 2 e máximo de 3 policiais, também contam como uma unidade; e o helicóptero conta como uma unidade. A unidade primária não deve abandonar a ocorrência sem motivo operacional. Unidades aéreas e de duas rodas têm prioridade na modulação quando necessário à condução da perseguição.",
      "18. Favela: incursões, patrulhamento e operações: Incursões em favela poderão ocorrer quando houver venda de biqueira ativa, grande quantidade de disparos ou quando um indivíduo em fuga entrar na favela. O patrulhamento de rotina em favela é restrito às unidades especializadas. Operações planejadas em favela somente poderão ocorrer mediante ordem do Comandante-Geral, que será responsável por organizar horário, efetivo e estratégia para que a operação seja realizada com segurança e coordenação.",
      "19. Conflitos entre organizações: Em conflitos entre organizações, a polícia deverá atuar para controlar ameaças iminentes à segurança pública e proteger terceiros. Em situações do sistema Dominas, a polícia não poderá intervir na disputa enquanto ela estiver ocorrendo dentro das regras específicas do sistema.",
      "",
      "6.2 REGRAS DO HOSPITAL — ALBERT EINSTEIN",
      "1. Neutralidade do Hospital: O Hospital é uma organização NEUTRA. Seus membros não podem escolher lados, compartilhar informações ou favorecer policiais ou criminosos. Enquanto estiverem em serviço, devem dedicar-se exclusivamente à medicina, não podendo portar armamentos nem participar de crimes.",
      "2. Proteção aos profissionais em serviço: Membros do Hospital não podem ser assaltados, sequestrados ou mortos enquanto estiverem devidamente em serviço, uniformizados e utilizando viatura caracterizada.",
      "3. Limites de atuação: O Hospital não atua como organização policial. Seus membros não podem prender, render ou desempenhar funções policiais contra criminosos.",
      "4. Reanimação: É proibido cancelar ou interromper propositalmente a animação de reanimação com o objetivo de acelerar o processo.",
      "5. Atendimento durante ações: Em caso de tiroteio ou ação em andamento, os membros do Hospital não têm autorização para reanimar indivíduos abatidos até o término da ação.",
      "6. Situação fora de serviço: Caso o profissional não esteja uniformizado e em veículo caracterizado do Hospital, será considerado um civil comum para fins de RP.",
      "7. Atendimento após tiroteio: Ao término de um tiroteio, cabe aos membros do Hospital avaliar os feridos e realizar o atendimento conforme os recursos disponíveis, a condição clínica e a possibilidade de sobrevivência de cada paciente.",
      "8. Receitas e medicamentos: É proibido o tráfico, desvio ou comércio irregular de receitas e medicamentos do Hospital.",
      "9. Afastamentos: Caso o membro fique afastado por mais de 3 dias, deverá comunicar sua ausência a um superior da instituição.",
      "10. Recusa de atendimento em situações abusivas: Os membros do Hospital não são obrigados a prestar atendimento em situações de desrespeito, Anti-RP, chamadas excessivas ou evidente falta de valorização da própria vida, sem prejuízo da análise administrativa do caso.",
      "11. Veículos durante o expediente: É proibido trabalhar ou realizar atendimentos utilizando veículo pessoal ou não autorizado durante o expediente. O profissional em serviço deverá utilizar viatura ou veículo autorizado pelo Hospital."
    ].join("\n")
  },
  ilegal: {
    title: "Manual do Ilegal — Facções, Organizações & Regulamento de Ações",
    content: [
      "REGRAS ILEGAL",
      "As regras abaixo regulamentam as atividades criminosas, organizações, facções, assaltos, sequestros, invasões e demais ações ilegais dentro do Distrito Paulista Roleplay. O bom senso, a valorização da vida e a qualidade do Roleplay devem prevalecer em todas as situações.",
      "",
      "ASSALTOS E SEQUESTROS",
      "• Toda ação criminosa deve prezar pela interpretação, negociação e coerência. Atitudes desproporcionais, abusivas ou realizadas sem qualquer construção de Roleplay poderão resultar em punição administrativa.",
      "",
      "REFÉNS",
      "• Reféns devem ser tratados como parte da situação de RP, sem abuso de mecânica e sempre com possibilidade razoável de negociação. A vida do refém deverá ser valorizada durante toda a ação.",
      "",
      "ORGANIZAÇÕES CRIMINOSAS",
      "Líderes e membros deverão manter uma conduta organizada, respeitando: Limites administrativos; Organizações rivais; Regras da Cúpula do Crime; Continuidade das histórias e do Roleplay da cidade.",
      "",
      "REGRAS DAS ORGANIZAÇÕES ILEGAIS",
      "1. Membros autorizados: Jogadores que não estejam devidamente cadastrados no painel da facção ou organização não serão considerados membros oficiais. Sendo assim, não poderão participar de invasões, defender território, defender favela ou base da organização.",
      "2. Venda de armas e drogas: A venda de armas e drogas para civis, organizações ou facções deverá respeitar a tabela de preços estabelecida pela cidade. Mantenha sempre o bom senso durante negociações.",
      "3. Reforços durante incursão policial: Após 20 minutos do início de uma incursão policial em favela, território ou qualquer outra base, fica proibida a entrada de novos reforços. A regra vale para ambos os lados: Polícia não poderá adicionar novos participantes e organização também não.",
      "4. Invasão de organização rival: Cada facção ou organização poderá realizar no máximo 1 invasão contra uma organização rival por semana, desde que exista motivo totalmente plausível dentro do RP, acompanhado de provas e registro no canal destinado no Discord da facção. Todas as facções são subordinadas à Cúpula do Crime. Siga as regras da Cúpula e prospere; quebre as regras e irá fracassar.",
      "5. Civis na defesa de organização: É proibida a utilização ou união com civis para defender favela, território, base ou organização/facção. Somente membros registrados poderão participar da defesa.",
      "6. Itens da organização: Os itens pertencentes à facção deverão obrigatoriamente ser armazenados no baú oficial da própria organização. Caso sejam retirados e armazenados indevidamente fora do baú, a situação poderá ser considerada roubo de patrimônio com julgamento pelo Tribunal da Cúpula.",
      "7. Abordagem policial: Sempre respeite a abordagem policial. É proibido interromper o RP para questionar procedimentos administrativos durante a abordagem. Não realize atitudes que você não faria na vida real. TENHA BOM SENSO E VALORIZE A VIDA.",
      "",
      "REGRAS DE AÇÕES CRIMINOSAS",
      "1. Crimes e efetivo policial: É proibido iniciar ações criminosas quando não houver, no mínimo, 2 policiais em patrulhamento, salvo quando alguma ação exigir efetivo maior. Veículos abandonados e abertos poderão ser furtados conforme regras, exceto em Área Safe.",
      "2. Cop Baiting: É extremamente proibido realizar Cop Baiting (provocar policiais, atrair policiais sem motivo, forçar perseguições ou criar situações apenas para matar policiais).",
      "3. Interferência externa em ações: Policiais ou criminosos que não estejam envolvidos em uma ação já iniciada não poderão interferir posteriormente, incluindo ações de lojas, bancos, joalheria e invasões em favela. Ações de rua poderão ocorrer conforme o contexto do RP.",
      "4. Pixel e exploração de bugs: É extremamente proibido utilizar bugs, falhas de pixel, glitches, falhas do mapa ou qualquer mecânica não intencional com a finalidade de obter vantagem sobre o adversário.",
      "5. Servidores públicos em serviço: É proibido roubar, assaltar ou sequestrar policiais, médicos e mecânicos enquanto estiverem efetivamente em serviço, observadas as regras específicas de cada profissão.",
      "6. Helicóptero em ação: Será permitido somente 1 helicóptero por lado em cada ação. Caso saia do perímetro de aproximadamente 1 quarteirão ou apresente fumaça/dano crítico, não poderá retornar para a mesma ação.",
      "7. Negociação com refém: Tudo que for acordado durante negociação deverá ser cumprido por ambos os lados. Pela vida de um refém poderá ser solicitado até R$ 100.000 em dinheiro sujo (excepcionalmente até R$ 350.000 autorizado pela Prefeitura para pessoa de grande relevância). Podem ser negociados veículos, alimentos ou outras condições permitidas. É PROIBIDO solicitar armas ou munições pela vida de um refém.",
      "8. Bloqueio de estabelecimento: É proibido posicionar veículos dentro ou diretamente na entrada de estabelecimentos com a finalidade de bloquear entrada/saída ou obter vantagem indevida durante a ação.",
      "9. Negociação antes do FF: Quando houver refém, será obrigatória uma negociação prévia antes da liberação do FF (Free Fire).",
      "10. Limite de ações grandes: Cada facção ou organização poderá realizar no máximo 1 ação grande por semana (Bancos, Joalheria, Banco Central, Nióbio e demais ações classificadas como grandes).",
      "11. Quantidade de assaltantes e reféns: No início da negociação deverá ser informada a quantidade real de assaltantes e de reféns envolvidos.",
      "12. Participação durante a ação: Em ações de bancos, joalheria, lojas e sequestros, somente poderão participar aqueles que já estavam envolvidos desde o início. É proibida a entrada posterior de terceiros para reforço.",
      "13. Fuga após negociação: Quando houver negociação de fuga, somente os participantes oficiais daquela ação poderão intervir durante a perseguição, com armamentos permitidos.",
      "14. Fuga limpa e risco assumido: Quando negociada fuga limpa, os criminosos têm direito ao acordado; entretanto, caso efetuem disparos ou ofereçam risco direto a policiais ou cidadãos, assumem automaticamente o risco de serem alvejados.",
      "15. Furto de veículos: É permitido furtar veículos estacionados e sem ninguém por perto, desde que respeitado o efetivo policial mínimo e fora de Área Safe.",
      "16. Favela durante ação ou invasão: Durante ação ou invasão em favela, é proibido entrar no interior de barracos apenas para se proteger e posteriormente retornar ao confronto.",
      "17. Horário para assaltar players na rua: Assaltos e roubos diretos contra outros jogadores na rua somente serão permitidos DAS 20:00 ATÉ ÀS 06:00. Fora desse horário fica proibido abordar jogadores com a finalidade de roubar itens, dinheiro, obrigar transferências ou ditar dita saidinha bancária. Ações próprias de bancos, lojas, caixas eletrônicos, registradoras e invasões seguem regras específicas.",
      "18. Sequestro para negociação: É permitido sequestrar jogadores para utilização como refém em bancos, lojas ou sequestro à mão armada. Entretanto, quando o player for utilizado exclusivamente como refém de negociação, É PROIBIDO retirar seus pertences.",
      "19. Retorno à ação: Após sair de uma ação ou deixar o perímetro de aproximadamente 1 quarteirão, o participante não poderá retornar à mesma ação.",
      "20. Refém fake: É proibido utilizar refém fake, combinar previamente com amigo ou simular risco inexistente para criar vantagem na negociação. O refém deverá estar realmente inserido na situação e sujeito aos riscos daquela ação.",
      "21. Saidinha bancária e transferências (Limite de 10%): Durante dita abordagem criminosa ou dita saidinha bancária, caso seja exigido que a vítima realize transferência, o criminoso poderá exigir no máximo 10% do valor disponível do jogador (ex: R$ 100.000 -> máx R$ 10.000; R$ 200.000 -> máx R$ 20.000; R$ 500.000 -> máx R$ 50.000; R$ 1.000.000 -> máx R$ 100.000). Proibido exigir mais de 10%, proibido fazer transferências seguidas ou dividir entre comparsas para burlar o limite. O limite de 10% é referente à ação inteira.",
      "22. Proibição de saque em zona vermelha: Fica proibido levar policiais para zona vermelha para saquear; o saque só é permitido quando a ação já teve início comprovado dentro da própria zona vermelha.",
      "",
      "TEMPO DAS AÇÕES",
      "• AÇÕES GRANDES (120 MINUTOS): Banco Central, Joalheria, Nióbio e Sequestro. Após 40 minutos do início da ação, a polícia poderá realizar a entrada ou intervenção necessária para encerrar a ocorrência.",
      "• AÇÕES PEQUENAS (15 MINUTOS): Lojinha e demais ações classificadas como pequenas. Após 15 minutos do início da ação, a polícia poderá realizar a intervenção necessária.",
      "• Observação: O tempo é estabelecido para evitar prolongamento excessivo. O bom senso deverá existir dos dois lados durante toda a ocorrência.",
      "",
      "ORIENTAÇÕES PARA AÇÕES COM REFÉM",
      "• Todos os criminosos participantes devem estar dentro do estabelecimento, banco ou perímetro definido para a ação, salvo quando a regra permitir participante externo.",
      "• É obrigatório informar a quantidade de assaltantes e de reféns durante a negociação.",
      "• Em sequestros ou ações com reféns, deverá existir RP prévio e negociação real.",
      "• A vida do refém é prioridade. Tudo que for negociado dentro das regras deverá ser cumprido por ambos os lados.",
      "",
      "REGRAS POR TIPO DE AÇÃO",
      "1. CAIXA REGISTRADORA: Mínimo de 2 policiais online | Proibido roubar de cima de veículo | Armamento permitido: arma branca e taser | Tempo livre | Sem necessidade de registro.",
      "2. CAIXA ELETRÔNICO: Mínimo de 2 policiais online | Proibido roubar de cima de veículo | Armamento permitido: arma branca, pistola ou revólver | Tempo livre | Sem necessidade de registro.",
      "3. LOJINHA / AMMUNATION / AÇOUGUE: Mínimo de 3 policiais e máximo de 4 policiais na ação | Criminosos: mínimo 2 e máximo 4 (máx 1 fora) | Armamento criminoso permitido: pistola (pistola automática é proibida) | Limite de 1 refém/pedido para negociação da saída.",
      "4. BANCOS CONVENCIONAIS: Efetivo: 5 a 8 policiais | Criminosos: 3 a 7 membros | Armamento: pelo menos 2 criminosos com arma de porte grande (fuzil, SMG ou calibre 12) | Limite de até 2 reféns.",
      "5. JOALHERIA: Efetivo: 5 a 10 policiais | Criminosos: 4 a 8 membros | Armamento: todos os criminosos com pelo menos 1 arma de porte grande (fuzil, SMG ou calibre 12) | Limite de até 2 reféns.",
      "6. NIÓBIO: Mínimo 8 policiais online para iniciar | Efetivo policial: 5 a 14 policiais | Criminosos: 5 a 14 membros com armas de porte grande (fuzil, SMG ou calibre 12) | Limite de até 2 reféns.",
      "7. BANCO CENTRAL: Mínimo 12 policiais online para iniciar | Efetivo policial: 8 a 14 policiais | Criminosos: 8 a 14 membros com pelo menos 1 arma de porte grande | Limite de até 3 reféns.",
      "8. SEQUESTRO À MÃO ARMADA: Máximo de 6 reféns por ação | Criminosos: mínimo 3 e máximo 10 criminosos | Efetivo policial na ação: 5 a 14 policiais | Efetivo policial mínimo em patrulha: 1 refém = 6 policiais; 2 reféns = 8; 3 reféns = 10; 4 reféns = 13; 5 reféns = 15; 6 reféns = 18 | Máximo de 1 pedido por refém | Proibido solicitar armas ou munições | Podem ser negociados dinheiro sujo, veículos e alimentos | Tudo que for negociado dentro das regras deverá ser cumprido.",
      "",
      "ÁREAS SAFE",
      "São consideradas Áreas Safe no Distrito Paulista: Praça, Hospital, Mecânicas, Concessionárias, Garagens Funcionais, Área interna do presídio, Locais de eventos oficiais, Restaurantes. Proibido iniciar ações criminosas contra outros jogadores em Área Safe ou utilizá-la como refúgio para escapar de perseguição.",
      "",
      "CONSIDERAÇÕES FINAIS",
      "As regras existem para garantir que o Ilegal do Distrito Paulista RP tenha disputa, estratégia e confronto, mas principalmente Roleplay de qualidade. Utilizar brechas nas regras, bugs ou mecânicas com a intenção de obter vantagem resultará em punição administrativa. VALORIZE SUA VIDA. RESPEITE O RP. TENHA BOM SENSO."
    ].join("\n")
  },
  codigo_penal: {
    title: "Código Penal Unificado & Lei de Armas e Drogas SP",
    content: [
      "Trânsito | Art. 218 | Alta Velocidade | 0 | R$ 1.500,00 | Limite de velocidade dentro da cidade de 120 km/h e de veículos de grande porte, 90 km/h. Aumenta-se R$ 25,00 a cada 20 km/h excedido.",
      "Trânsito | Art. 175 | Direção Perigosa | 0 | R$ 3.000,00 | Uso negligente ou imprudente de um veículo.",
      "Trânsito | Art. 181 | Estacionar em local proibido | 0 | R$ 2.500,00 | Deixar o veículo em local indevido.",
      "Trânsito | Art. 01 | Pousar em local proibido ou sem designação | 0 | R$ 30.000,00 | Pousar veículos aéreos fora de locais adequados e seguros.",
      "Trânsito | Art. 02 | Manobra imprudente com aeronave | 0 | R$ 25.000,00 | Utilizar Aeronave de forma imprudente.",
      "Trânsito | Art. 24 | Veículo Abandonado | 0 | R$ 1.750,00 | Abandonar veículo em local indevido.",
      "Trânsito | Art. 186 | Trafegar na contra mão | 0 | R$ 2.000,00 | Conduzir na contra mão da via.",
      "Trânsito | Art. 135 | Omissão de Socorro | 15 | R$ 4.000,00 | Quando o causador do dano ou lesão ao cidadão, abandona o local sem prestar socorro.",
      "Trânsito | Art. 180 | Falta de combustível em vias | 0 | R$ 6.780,00 | Ter seu veículo imobilizado na via por falta de combustível.",
      "Trânsito | Art. 162 | Dirigir sem habilitação | 0 | R$ 3.000,00 | Dirigir sem possuir habilitação, podendo ser aplicado a detenção do veículo.",
      "Trânsito | Art. 210 | Ultrapassar blitz | 10 | R$ 3.470,00 | Transpor, sem autorização, bloqueio viário policial.",
      "Trânsito | Art. 225 | Praticar corrida ilegal | 0 | R$ 5.000,00 | Praticar corrida ilegal. Entende-se por corrida ilegal aquela qual obtém-se dinheiro ilícito, devendo ser aplicado a detenção do veículo e revogação da habilitação.",
      "Trânsito | Art. 311 | Clonagem de placas | 0 | R$ 5.000,00 | Adulterar placa de veículo automotor, devendo ser aplicado a detenção do veículo.",
      "Trânsito | Art. 244-A | Conduzir motocicleta sem usar capacete | 0 | R$ 1.750,00 | Trafegar com motocicleta sem o uso do capacete.",
      "Trânsito | Art. 230 | Conduzir veículo com as taxas atrasadas | 0 | R$ 2.300,00 | Conduzir veículo com as taxas atrasadas, podendo ser aplicado a detenção do veículo.",
      "Trânsito | Art. 244-B | Conduzir motocicleta fazendo malabarismo | 0 | R$ 1.900,00 | Conduzir motocicleta fazendo malabarismo ou se equilibrar em apenas uma das rodas, podendo ser aplicado a revogação da habilitação.",
      "Crimes Contra a Pessoa | Art. 121 | Homicídio | 30 | R$ 3.000,00 | Matar alguém.",
      "Crimes Contra a Pessoa | Art. 121-A | Homicídio de funcionário público | 40 | R$ 6.300,00 | Matar funcionário público, durante a sua função ou em razão dela.",
      "Crimes Contra a Pessoa | Art. 121-B | Homicídio culposo | 10 | R$ 800,00 | Matar alguém em razão de imprudência, negligência ou imperícia.",
      "Crimes Contra a Pessoa | Art. 129 | Lesão corporal | 15 | R$ 1.500,00 | Ofender a integridade física ou saúde de outrem.",
      "Crimes Contra a Pessoa | Art. 138 | Calúnia | 10 | R$ 2.000,00 | Imputar fato considerado criminoso de alguém.",
      "Crimes Contra a Pessoa | Art. 139 | Difamação | 10 | R$ 2.000,00 | Imputar fato ofensivo à sua reputação de alguém.",
      "Crimes Contra a Pessoa | Art. 140 | Injúria | 10 | R$ 2.000,00 | Ofender a dignidade ou decoro de alguém.",
      "Crimes Contra a Pessoa | Art. 147 | Ameaça | 15 | R$ 2.500,00 | Ameaçar alguém, por qualquer meio, a causar mal injusto e grave.",
      "Crimes Contra a Pessoa | Art. 148 | Sequestro e cárcere privado | 20 | R$ 4.500,00 | Privar alguém de sua liberdade, mediante sequestro ou cárcere privado.",
      "Crimes Contra a Pessoa | Art. 121-C | Feminicídio | 50 | R$ 10.200,00 | Homicídio doloso praticado contra a mulher por razões da condição do sexo feminino.",
      "Crimes Contra a Pessoa | Art. 215 | Importunação sexual | 40 | R$ 5.000,00 | Praticar contra alguém e sem a sua anuência ato libidinoso com o objetivo de satisfazer a própria lascívia ou a de terceiro.",
      "Crimes Contra a Pessoa | Art. 286 | Incitação e/ou apologia ao crime | 8 | R$ 750,00 | Incitar, estimular ou fazer, publicamente, apologia a prática de crimes.",
      "Crimes Contra a Pessoa | Art. 150 | Violação de domicílio | 7 | R$ 1.300,00 | Entrar ou permanecer, contra vontade de quem tem direito, em casa ou dependência.",
      "Crimes Contra o Patrimônio | Art. 155 | Furto | 10 | R$ 2.500,00 | Subtrair, para si ou para outrem, coisa alheia móvel.",
      "Crimes Contra o Patrimônio | Art. 157 | Roubo | 20 | R$ 4.000,00 | Subtrair coisa alheia móvel, para si ou outrem, mediante violência ou grave ameaça.",
      "Crimes Contra o Patrimônio | Art. 157-A | Subtração de viatura | 100 | R$ 20.000,00 | Subtrair, de qualquer forma, viatura ou carro oficial.",
      "Crimes Contra o Patrimônio | Art. 157-B | Roubo seguido de morte (latrocínio) | 60 | R$ 8.000,00 | Subtrair coisa alheia móvel, para si ou outrem, mediante violência ou grave ameaça, com resultado morte.",
      "Crimes Contra o Patrimônio | Art. 168 | Apropriação indébita | 10 | R$ 3.000,00 | Apropriar-se de coisa alheia móvel, de que tem posse ou detenção.",
      "Crimes Contra o Patrimônio | Art. 171 | Estelionato | 12 | R$ 2.500,00 | Obter, para si ou outrem, vantagem ilícita, em prejuízo alheio, por meio de fraude, erro, artifício ou ardil.",
      "Crimes Contra o Patrimônio | Art. 126 | Desmonte de veículos | 10 | R$ 2.500,00 | Adquirir, receber, transportar, ofertar, conduzir ou ocultar a desmontagem de veículo automotor terrestre.",
      "Crimes Contra o Patrimônio | Art. 180 | Receptação | 10 | R$ 2.500,00 | Adquirir, receber, transportar, conduzir ou ocultar, em proveito próprio ou alheio, coisa que saiba ser produto de crime.",
      "Crimes Contra a Ordem Pública | Art. 200-A | Roupas Policiais | 50 | R$ 5.000,00 | Utilizar qualquer acessório ou roupa de uso exclusivamente policial.",
      "Crimes Contra a Ordem Pública | Art. 200-B | Roupas Militares | 0 | R$ 5.000,00 | Utilizar qualquer acessório ou roupa de cunho militar (coldres, coletes) em locais públicos como Hospital, Mecânicos, Praça, Delegacia.",
      "Crimes Contra a Ordem Pública | Art. 200-C | Ocultação facial | 0 | R$ 5.000,00 | Utilizar qualquer acessório ou roupa que cubra totalmente o rosto em locais públicos como Hospital, Mecânicos, Praça, Delegacia.",
      "Crimes Contra a Ordem Pública | Art. 201 | Produtos ilícitos | 13 | R$ 2.000,00 | Portar ou possuir objetos ilícitos, conforme decreto judicial.",
      "Crimes Contra a Ordem Pública | Art. 288 | Associação criminosa | 15 | R$ 2.000,00 | Associar-se em 03 ou mais pessoas, para o fim específico de cometer crimes.",
      "Crimes Contra a Ordem Pública | Art. 289 | Dinheiro ilícito | 18 | R$ 5.000,00 | Portar dinheiro marcado.",
      "Crimes Contra a Ordem Pública | Art. 299 | Falsidade ideológica | 10 | R$ 1.750,00 | Atribuir, para si ou terceiro, falsa identidade, no intuito de obter vantagem ou prejudicar outrem.",
      "Crimes Contra a Ordem Pública | Art. 330 | Desobediência | 10 | R$ 1.700,00 | Desobedecer à ordem legal de funcionário público.",
      "Crimes Contra a Ordem Pública | Art. 331 | Desacato | 12 | R$ 1.500,00 | Desacatar funcionário público no exercício da função ou em razão dela, com intuito de menosprezá-lo.",
      "Crimes Contra a Ordem Pública | Art. 333 | Corrupção | 20 | R$ 3.000,00 | Obter, para si ou para outrem, vantagem indevida, em razão da função pública. Parágrafo único: o fato constitui crime, salvo quando não houver violação às regras da cidade.",
      "Crimes Contra a Ordem Pública | Art. 333-A | Suborno | 15 | R$ 2.600,00 | Oferecer ou prometer vantagem indevida a funcionário público.",
      "Crimes Contra a Ordem Pública | Art. 339 | Denunciação caluniosa | 12 | R$ 2.000,00 | Dar causa à instauração de inquérito policial ou processo judicial, contra alguém, imputando-lhe crime de que sabe ser inocente.",
      "Crimes Contra a Ordem Pública | Art. 13.260 | Terrorismo | 100 | R$ 10.000,00 | O terrorismo consiste na prática por um ou mais indivíduos dos atos por razões de terrorismo contra órgãos públicos quando cometidos com a finalidade de provocar terror social ou generalizado.",
      "Crimes Contra a Ordem Pública | Art. 342 | Falso testemunho | 12 | R$ 2.500,00 | Fazer afirmação falsa, negar ou calar a verdade, na posição de testemunha.",
      "Crimes Contra a Ordem Pública | Art. 351 | Fuga de pessoa custodiada | 12 | R$ 2.000,00 | Promover ou facilitar fuga de pessoa custodiada.",
      "Crimes Contra a Ordem Pública | Art. 355 | Abuso de autoridade | 30 | R$ 5.000,00 | Abusar da posição pública, no intuito de obter vantagem ou promover injusto à outrem, conforme decreto judicial.",
      "Crimes Contra a Ordem Pública | Art. 357 | Obstrução de Justiça | 12 | R$ 2.000,00 | Atrapalhar o andamento de instrução processual ou de ordem judicial.",
      "Lei de Armas e Drogas | Art. 12 | Porte ou posse ilegal de arma classe 1 | 13 | R$ 2.000,00 | Porte ou posse ilegal de armamento semi-automático.",
      "Lei de Armas e Drogas | Art. 16 | Porte ou posse ilegal de arma classe 2 | 15 | R$ 3.000,00 | Porte ou posse ilegal de armamento automático.",
      "Lei de Armas e Drogas | Art. 17 | Tráfico de munições | 8 | R$ 1.800,00 | Portar munições, de qualquer calibre, dependerá da comprovação do dolo da comercialização/traficância para configurar o crime. Parágrafo único: Acima de 10 unidades, já configura o delito, independentemente da finalidade.",
      "Lei de Armas e Drogas | Art. 18 | Tráfico de armamento | 20 | R$ 3.000,00 | Portar mais de 02 armamentos, independente do calibre.",
      "Lei de Armas e Drogas | Art. 33 | Tráfico de drogas | 10 | R$ 1.500,00 | Posse ou porte de entorpecentes, permitindo-se o máximo de 04 unidades."
    ].join("\n")
  },
  historia: {
    title: "Nossa História — Distrito Paulista RP",
    content: [
      "O Distrito Paulista nasceu da união de um grupo de amigos que estava cansado de passar por diferentes cidades de RP e encontrar sempre os mesmos problemas: abuso de poder na staff, suporte ruim e uma gestão autoritária, que não valorizava o tempo e a dedicação de cada jogador.",
      "",
      "Foi dessa insatisfação que surgiu a vontade de construir uma cidade com respeito, diálogo e compromisso com a comunidade. Um lugar onde os jogadores fossem ouvidos e cada história tivesse espaço para acontecer.",
      "",
      "Nossa proposta é o Medium RP, com foco em interpretação, imersão e responsabilidade. Queremos histórias bem construídas, mas também uma experiência acolhedora e divertida. Nosso compromisso é com o RP, e nossa maior prioridade é o bem-estar de todos os jogadores.",
      "",
      "Para isso, desenvolvemos sistemas próprios e recursos únicos, pensados para trazer novas possibilidades e tornar a cidade cada vez mais imersiva. Seguimos abertos a críticas e sugestões, porque acreditamos que um servidor cresce quando sua comunidade participa dessa construção.",
      "",
      "Aqui, seu tempo tem valor, sua opinião tem espaço e sua história faz parte da nossa.",
      "",
      "Sejam bem-vindos ao Distrito Paulista!"
    ].join("\n")
  },
  estrutura_cidade: {
    title: "Estrutura da Cidade — Facções & Forças de São Paulo",
    content: [
      "ESTRUTURA DAS ORGANIZAÇÕES E CORPORAÇÕES",
      "Cada corporação e organização no Distrito Paulista possui regimento próprio, cadeia de comando e procedimentos de Roleplay realistas.",
      "",
      "PMESP (Polícia Militar de SP): Patrulhamento ostensivo, Força Tática, ROTA, ROCAM e RPM com procedimentos operacionais reais da corporação.",
      "POLÍCIA CIVIL (PCESP): DEIC, GARRA e equipes de inteligência focadas em investigação de facções, mandados judiciais e perícia criminal.",
      "PRF (Polícia Rodoviária Federal): Fiscalização de rodovias estaduais e federais, combate ao contrabando de armas e drogas, interceptações em alta velocidade e apoio com o NOE.",
      "O ILEGAL & FACÇÕES: Disputa de territórios de favela, venda de drogas, tráfico de armamento pesado e ações de grande porte com regras rígidas de Fair Play.",
      "HOSPITAL & SAMU 192: Equipe médica neutra prestando atendimento a civis, policiais e criminosos em serviço 24 horas ininterruptas.",
      "MECÂNICAS & CULTURA DE RUA: Preparações de motor, funilaria, suspensão a ar, pinturas customizadas e os maiores encontros automotivos da capital."
    ].join("\n")
  },
  sp_noite: {
    title: "São Paulo à Noite — Onde Ação e Roleplay se Encontram",
    content: [
      "DA PERIFERIA AOS BAIRROS NOBRES",
      "O Distrito Paulista foi desenhado com foco total na experiência visual e imersiva: sem texturas estouradas, sem menus poluídos e com um HUD minimalista para manter sua imersão em 100%.",
      "",
      "Das avenidas iluminadas aos becos das comunidades, cada esquina conta uma história de poder, lealdade e sobrevivência na maior metrópole do Brasil.",
      "Otimização impecável garantindo 120 FPS estáveis mesmo em confrontos e perseguições intensas."
    ].join("\n")
  },
  guia_sobrevivencia: {
    title: "Guia de Sobrevivência — Teclas & Comandos Essenciais do Jogador",
    content: [
      "K | Abrir Smartphone | Contatos, transferências bancárias, chamados do SAMU e táxi.",
      "\" | Abrir Inventário | Mochila, bolsos, itens rápidos e uso de equipamentos.",
      "F11 | Menu de Animações (Emotes) | Centenas de poses, danças e interações corporais de RP.",
      "G | Cinto de Segurança | Evita ejeção do para-brisa em colisões de alta velocidade.",
      "L | Trancar / Destrancar Veículo | Alarme e travas do carro próprio ou viatura autorizada.",
      "F8 | Console de Conexão | Para comandos de conexão, reset de voz e diagnóstico.",
      "B | Apontar o Dedo | Interação gestual para indicar direção e objetos.",
      "CAPS | Falar no Rádio / Walkie-Talkie | Comunicação de voz com frequência militar e facções."
    ].join("\n")
  }
};

export const INITIAL_DEMO_USERS = [
  { id: "user-ceo-01", name: "Blaze / Lomba / Morgan", email: "ceo@distritopaulista.com", role: "ceo", status: "active" },
  { id: "user-dir-02", name: "Mariana Torres | ID: 12", email: "diretor@distritopaulista.com", role: "diretor", status: "active" },
  { id: "user-ger-03", name: "Carlos 'Kadu' Lima | ID: 45", email: "gerente@distritopaulista.com", role: "gerente", status: "active" },
  { id: "user-adm-04", name: "Felipe 'Falcon' Rocha | ID: 88", email: "admin@distritopaulista.com", role: "administrador", status: "active" },
  { id: "user-mod-05", name: "Beatriz 'Bia' Ramos | ID: 110", email: "moderador@distritopaulista.com", role: "moderador", status: "active" },
  { id: "user-sup-06", name: "Lucas Menezes | ID: 230", email: "suporte@distritopaulista.com", role: "suporte", status: "active" }
];

export const INITIAL_DEMO_APPLICATIONS = [
  {
    id: "app-101",
    game_name: "Thiago 'Coruja' Ramos | ID: 1042",
    discord_tag: "coruja_rp#4412",
    age: 21,
    desired_role: "suporte",
    availability: "Todos os dias das 18h às 00h",
    experience: "Mais de 1.800 horas de FiveM. Fui suporte durante 6 meses no servidor SP Capital e conheço todos os comandos de atendimento.",
    scenario1: "Gravo clipe, aplico freeze se necessário, puxo para atendimento e aplico advertência/banimento conforme manual.",
    scenario2: "A integridade da staff vem em primeiro lugar. Amizades não anulam infrações.",
    motivation: "Gosto de organizar e tirar dúvidas dos jogadores iniciantes.",
    status: "pending",
    created_at: "2026-10-04T22:15:00Z",
    reviewer: null,
    reviewed_at: null
  },
  {
    id: "app-102",
    game_name: "Larissa Silveira | ID: 843",
    discord_tag: "lari_silveira",
    age: 24,
    desired_role: "moderador",
    availability: "Segunda a Sexta das 14h às 20h",
    experience: "3 anos de FiveM, experiência em triagem de denúncias e tickets de atendimento.",
    scenario1: "Converso calmamente, analiso clipes dos envolvidos e busco solução pacífica de acordo com as diretrizes.",
    scenario2: "Tratamento estritamente imparcial com notificação da infração.",
    motivation: "Ajudar a manter a cidade limpa de anti-RP e VDM.",
    status: "approved",
    created_at: "2026-10-03T18:30:00Z",
    reviewer: "Blaze / Lomba / Morgan (CEO)",
    reviewed_at: "2026-10-04T10:00:00Z"
  },
  {
    id: "app-103",
    game_name: "Rodrigo Pires | ID: 310",
    discord_tag: "pires_gamer",
    age: 15,
    desired_role: "suporte",
    availability: "Finais de semana apenas",
    experience: "Pouca experiência, jogando há alguns meses.",
    scenario1: "Gritaria com quem fizesse VDM.",
    scenario2: "Tentaria ajudar meu amigo.",
    motivation: "Ter comandos de admin.",
    status: "rejected",
    created_at: "2026-10-02T11:00:00Z",
    reviewer: "Mariana Torres (Diretoria)",
    reviewed_at: "2026-10-02T16:40:00Z"
  }
];

export const INITIAL_DEMO_LOGS = [
  {
    id: "log-1",
    action: "Sistema Inicializado",
    user: "Sistema Central",
    details: "Ecossistema administrativo do Distrito Paulista ativo e sincronizado",
    timestamp: new Date().toISOString()
  },
  {
    id: "log-2",
    action: "Homologação de Candidatura",
    user: "Blaze / Lomba / Morgan (CEO)",
    details: "Candidatura de Larissa Silveira (ID: 843) aprovada para entrevista",
    timestamp: "2026-10-04T10:00:00Z"
  }
];

export const DEFAULT_PERMISSIONS = {
  can_view_applications: { label: "Visualizar Candidaturas de Staff", suporte: false, moderador: true, administrador: true, gerente: true, diretor: true, ceo: true },
  can_review_applications: { label: "Aprovar / Recusar / Avaliar Candidaturas", suporte: false, moderador: false, administrador: false, gerente: true, diretor: true, ceo: true },
  can_delete_applications: { label: "Excluir Candidaturas do Sistema", suporte: false, moderador: false, administrador: false, gerente: false, diretor: true, ceo: true },
  can_edit_rules: { label: "Modificar e Publicar Regras e História", suporte: false, moderador: false, administrador: false, gerente: false, diretor: true, ceo: true },
  can_manage_staff: { label: "Promover / Rebaixar / Gerenciar Membros", suporte: false, moderador: false, administrador: false, gerente: false, diretor: true, ceo: true },
  can_create_accounts: { label: "Criar Novos Logins de Staff", suporte: false, moderador: false, administrador: false, gerente: false, diretor: false, ceo: true },
  can_view_audit_logs: { label: "Acessar Trilha de Auditoria", suporte: false, moderador: false, administrador: false, gerente: true, diretor: true, ceo: true },
  can_clear_audit_logs: { label: "Limpar Histórico de Auditoria", suporte: false, moderador: false, administrador: false, gerente: false, diretor: false, ceo: true }
};

export const ROLE_DISPLAY_NAMES = {
  ceo: "CEO (Master)",
  diretor: "Diretor Geral",
  gerente: "Gerente Operacional",
  administrador: "Administrador",
  moderador: "Moderador",
  suporte: "Suporte",
  player: "Cidadão"
};

export const ROLE_EMOJIS = {
  ceo: "👑",
  diretor: "⚜️",
  gerente: "💼",
  administrador: "⚖️",
  moderador: "🛡️",
  suporte: "🎧"
};
